### ISSUE TITLE
Video overlaps side bar

### ISSUE THREAD

**Issue by efrapp** [ndjerrou/VideoPlayer_Youtube-Like#2]
<img width="1401" alt="Screen Shot 2019-06-04 at 7 54 19 PM" src="https://user-images.githubusercontent.com/698811/58922925-d08b8680-8702-11e9-8a2b-f8bc61e065d6.png">

Please fix this error, I checked it on Firefox too and the error is similar.

**Comment by ndjerrou** [comment]
Hello,

Thanks for ur feedback.

We corrected it a few minutes ago, can u check plz ?

We had a bad width property using with a width of -370px for the related videos ^^

Thanks a lot.

**Comment by efrapp** [comment]
Hi team,

<img width="1424" alt="Screen Shot 2019-06-05 at 5 53 08 PM" src="https://user-images.githubusercontent.com/698811/58995749-13109a00-87bb-11e9-8ede-a4d8adbd6ed8.png">

You made some improvements but the error is still there. I'm going to put some suggestion in your code about ideas on how to fix this.

**Comment by ndjerrou** [comment]
Hello there,

We've made the changes request, may u check?

Ans i would like to ask u , what is the difference between making a pull request and the issues section?

This is not clear for me.

Thanks for your feedback

**Comment by efrapp** [comment]
Hi @ndjerrou how are you?
The Issue section is when you can point out problems the project has and you can reference them on reviews in a pull request. Let me know if I was clear.

Ok now the error was fixed and I'm going to close this issue.

**Comment by efrapp** [comment]
Error fixed.
